# Generated by Django 4.2.1 on 2023-06-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='TarefaModel',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UsuarioModel',
        ),
    ]
